name: Backup Repository

on:
  push:
    branches: [ main ]

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to backup repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote add backup https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/S1mp3r/backup-engineering-prompt-course.git
          git push --force backup main
